### ISSUE TITLE
Electrum dash 2.4.1 Upgrade to 2.5.1 - help!

### ISSUE THREAD

**Issue by Mrtibbs316** [dashpay/electrum-dash-old#100] opened 2017-03-14 19:35 UTC
Hello .

I have an electrum dash wallet - version 2.4.1 - i recently tried to move some dash coins but i get an error message saying i cant do this, and need to upgrade to 2.5.1.

Only thing is there is no link to a 2.5.1 upgrade. ALmost like its not even out yet?

Can someone please advise how i get round this?

Please note my knowledge is pretty basic, but if someone can provide a some assistance i would really appreciate it.

Thanks people

**Comment by bauerj** [comment] 2017-03-14 19:59
Duplicate of #99

**Comment by fyipal** [comment] 2017-03-15 10:37
Got the same issue. Please help; It's like money locked in a safe without keys?

**Comment by parparanga** [comment] 2017-03-15 12:55
Please help and  inform us with the correct way to upgrade from 2.4.1.

**Comment by parparanga** [comment] 2017-03-15 13:02
When I look into the release notes the most recent version should be : Release 2.6.4

**Comment by parparanga** [comment] 2017-03-15 13:03
Please help and inform us with the correct way to upgrade from 2.4.1. to 2.6.4 .
Thank you.

**Comment by schinzelh** [comment] 2017-03-15 13:07
There is currently only a pre-release of 2.6.4 available for Windows, if you'd like to give it a try:

--> https://dashpay.atlassian.net/builds/browse/ELMW-DEV-121/artifact/JOB1/electrum-dash.exe/electrum-dash.exe

**Comment by thelazier** [comment] 2017-03-15 13:14
Please check #95

**Comment by parparanga** [comment] 2017-03-15 17:36
Hello Holger

 

My wallet seed created during the installation of version 2.4.1 is 13 words!

 

Can I insert these 13 words in version 2.6.4 ?

 

 

 

When I install the newest version, is it necessary to remove something from the Roaming directory?

 

Do I need to export the private keys first, before the update?

 

I need to be careful, because this wallets contains 60 DASH.

 

Please advise

 

Best regards

P.P.

 

Van: Holger Schinzel [mailto:notifications@github.com] 
Verzonden: woensdag 15 maart 2017 14:07
Aan: dashpay/electrum-dash
CC: parparanga; Comment
Onderwerp: Re: [dashpay/electrum-dash] Electrum dash 2.4.1 Upgrade to 2.5.1 - help! (#100)

 

There is currently only a pre-release of 2.6.4 available for Windows, if you'd like to give it a try:

--> https://dashpay.atlassian.net/builds/browse/ELMW-DEV-121/artifact/JOB1/electrum-dash.exe/electrum-dash.exe

**Comment by Mrtibbs316** [comment] 2017-03-15 22:32
The fix of changing the server manual  to electrum masternode io\electrumdash.org server has not worked.

Can anyone advise in Lamens terms if there is any way to transfer coins from electrum dash to my computer, then to another wallet, or answer above question so i can run the newer version and then re connect to my wallet through that?

**Comment by thelazier** [comment] 2017-03-16 07:44
@Mrtibbs316 ,

> Can anyone advise in Lamens terms if there is any way to transfer coins from electrum dash to another wallet, or answer above question so i can run the newer version and then re connect to my wallet through that?
Yes, you have following options
1. Remember your backup seeds, you can install newer version and recover the seeds.
2. Export Private Keys from Electrum Dash, then you can import these key into newer version of Electrum-Dash or Dash Core Wallet later.
Btw, please also check https://github.com/dashpay/electrum-dash/issues/95#issuecomment-281944464 just in case you may encounter the same situation.

**Comment by nmarley** [comment] 2019-02-11 14:01
Hi, the current Electrum Dash fork is maintained here: https://github.com/akhavr/electrum-dash

Please use that repo and report there if you have any issues.

**Closed by nmarley** 2019-02-11 14:01 UTC
